name: pnpm test
on:
  push:
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        with:
          bun-version: latest
      - run: bun install
      - run: bun test --coverage
      - run: |
          cd packages/nirina.js
          bun run build
      - run: |
          cd packages/playground
          bun run build
